class API_Connection_Error(Exception):
    """
    Возникает если не получается подключить по API к LLM
    """
    pass